alias gc="git commit -m"
alias gp="git push"
alias gco="git checkout"
alias gls="git log --oneline -12"
alias c="clear"
alias b="cd .."
alias update="git fetch origin main && git rebase origin/main"
alias rebuild="docker compose down -v --remove-orphans && docker compose build --no-cache"
alias dco="devcontainer open ."
alias grat="c && cd ~/dev/build-people && dco && c"
alias g="git status"
alias ga="git add ."
alias switch="git switch -c"
alias amend="git commit --amend --no-edit"
alias wip="ga && git commit -m 'wip' --no-verify"
alias dewip="git reset HEAD~1"
alias gcont="ga && git rebase --continue"
alias gst="git stash"
alias gsa="git stash apply"
alias cpr="gh pr create -w"
alias py="uv run python manage.py"
alias dca='docker attach $(docker ps --filter "name=build-people-web" --format "{{.ID}}" | head -n 1)'
alias reload="source  ~/.bashrc"
alias venv="source .venv/bin/activate"
alias dj="djlint . --reformat"
function hotfix() {
    switch "$1"
    ga
    gc "hotfix"
    update
    git push --set-upstream origin "$1"
}
