services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - ./theme/static_src:/app/theme/static_src
      - ./theme/static:/app/theme/static
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
