services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    container_name: build-people-web
    volumes:
      - .:/app
      - ./theme/static_src:/app/theme/static_src
      - ./theme/static:/app/theme/static
      - static_volume:/app/staticfiles
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development
    networks:
      - dev

  db:
    image: postgres:16
    container_name: build-people-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: build-people-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - dev

  mailhog:
    image: mailhog/mailhog
    container_name: build-people-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - dev

volumes:
  postgres_data:
  pgadmin_data:
  static_volume:

networks:
  dev:
