[project]
name = "gratify-2"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = [
  "django ~=5.1",
  "django-debug-toolbar ~=4.4",
  "gunicorn ~=23.0",
  "psycopg[binary] ~=3.2",
  "whitenoise ~=6.7",
  "django-tailwind>=3.8.0",
  "crispy-tailwind>=1.0.3",
  "hx-requests>=0.35.5",
]

[dependency-groups]
dev = [
  "cookiecutter>=2.6.0",
  "djlint>=1.36.4",
  "python-dotenv>=1.0.1",
  "ruff>=0.11.2",
  "typing_extensions ~=4.12",
]

[tool.djlint]
profile = "django"
reformat = true
max_line_length = 105
preserve_blank_lines = false
attr_sort = true
quote_convert = "double"
blank_line_before_tag = "block"
blank_line_after_tag = "endblock, extends"
format_attribute_template_tags = true
preserve_leading_space = false

[tool.ruff]
line-length = 105
indent-width = 4
exclude = [
  ".git",
  ".pytest_cache",
  ".ruff_cache",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]

[tool.ruff.lint]
extend-select = ["Q"]

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
exclude = [
  "users/migrations/**",
  "gratify/migrations/**",
]
