# Generated by Django 5.1.7 on 2025-04-09 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('build_people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeinvite',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='build_people.company'),
        ),
        migrations.AddField(
            model_name='recognition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recognition',
            name='hearts',
            field=models.ManyToManyField(blank=True, help_text='Users who liked this recognition', related_name='hearted_recognitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recognition',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recognitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recognitioncomment',
            name='recognition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='build_people.recognition'),
        ),
        migrations.AddField(
            model_name='recognitioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
