# Generated by Django 5.1.7 on 2025-04-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_people', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='build_people.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recognition',
            name='core_values',
            field=models.ManyToManyField(related_name='recognitions', to='build_people.corevalue'),
        ),
        migrations.AddConstraint(
            model_name='corevalue',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_core_value'),
        ),
    ]
