# Generated by Django 5.1.7 on 2025-03-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gratify", "0003_recognition_recognitioncomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recognitioncomment",
            options={"ordering": ["-created_at"]},
        ),
    ]
